### PR TITLE
Add runner user to sudoers and bump Docker version

### PR DESCRIPTION
**Pull request by vitobotta**
Hi, a small PR as discussed in #22. Thanks

### CODE REVIEW

**Comment by mumoshu** [comment]
@vitobotta Thanks! I'll review this asap.

@summerwind Should we add a field to the Runner spec to make this configurable? WDYT?

**Comment by vitobotta** [comment]
Ehm... I tested this image locally and I got the user in the sudoers group etc. But how can I use my image for the runner now, while this gets merged? I need to be root to investigate some issues, especially networking related. There seems to be a networking issue with Docker in Docker, and often my build fails in the runner because it cannot connect to some hosts to download packages etc. Any idea?

**Comment by vitobotta** [comment]
I have found some references lke https://discuss.istio.io/t/connection-issues-with-docker-build-inside-a-kubernetes-pod/5761 where they say that using the host network would solve these networking issues. Is this possible?

**Comment by vitobotta** [comment]
I solved the networking issue.... but I still don't know how to use my image for the runner :(

**Comment by mumoshu** [comment]
Please specify the `image` field in your runner to the name of the image you've docker-pushed https://github.com/summerwind/actions-runner-controller/blob/master/api/v1alpha1/runner_types.go#L40

**Comment by vitobotta** [comment]
@mumoshu   It worked, thannks!

**Comment by summerwind** [comment]
Thanks for the PR! 

In the GitHub's runner environment allows us to use `sudo` with no password. So, this change looks good to me 👍 
See also: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#administrative-privileges-of-github-hosted-runners

In the future, it seems better to make the file system of the Runner container image the same as GitHub's runner environment.

**Pull request merged**
