### PR TITLE
Add support for enterprise runners

### LINKED ISSUE #289: Add support for enterprise runners
readme currently says `Enterprise level runners are not working yet as there's no API definition for those.`

However, that is not true anymore. APIs are published and can be seen in https://docs.github.com/en/rest/reference/enterprise-admin#create-a-registration-token-for-an-enterprise for instance

### PR DESCRIPTION
**Pull request by zetaab**
waiting for PR https://github.com/google/go-github/pull/1789 and after that I can verify this

fixes #289

### CODE REVIEW

**Comment by mumoshu** [comment]
@zetaab Out of curiosity, how can I test this myself? 😃

**Comment by zetaab** [comment]
@mumoshu at least github enterprise server 3.0 rc1/rc2 do have this.

**Comment by zetaab** [comment]
I have tested this against our GHE installation and it do work.

**Comment by zetaab** [comment]
@mumoshu can you review this

**Comment by callum-tait-pbx** [comment]
Might be worth adding to the README.md what the minimum GitHub Enterprise version is, or a link to a GitHub page that illustrates this. I can see people raising questions against the repository about it not working with a GitHub Enterprise version that isn't supported due to APIs.

It's probably worth adding too the fact that this is an open source project and so supporting GitHub Enterprise is a best endeavours effort from the maintainers and they are reliant on the community for testing etc for the most part. @mumoshu  any thoughts?

**Review by mumoshu — APPROVED** [review]
Code LGTM. BTW, can I take the concept of "enterprise" as the broader version of "organization", right? 😃 

@callum-tait-pbx Thanks as always for your support. Definitely, testing and maintenance was my concern. The final update on README made by @zetaab seems to nicely communicate that.

Thanks a lot for your contribution @zetaab!

**Pull request merged**
