### PR TITLE
Clarify instructions for getting a token

### PR DESCRIPTION
**Pull request by acj**
Finding a token was confusing the first time -- is it a personal access token, or something else? But the process is straightforward.

### CODE REVIEW

**Comment by mumoshu** [comment]
@acj Hey! Thanks for this. But it should be a personal access token.

Please see https://github.com/summerwind/actions-runner-controller/blob/d4c849ee091076d233e14217d09e5f014ba8efa8/controllers/runner_controller.go#L251 - the whole purpose of this project is to automate creation of registration tokens in favor of you, and your personal access token, so that you don't have to.

I obtained my personal access token from https://github.com/settings/tokens, giving it `repo` and `workflow` scopes.

If that works for you as well, I think this part of the doc can be better updated to note that where to create the token and what scopes you should provide.

**Comment by acj** [comment]
Ah, my mistake. Fixed.

I'm not having any luck with a PAT that has repo and workflow scopes either:

```
Events:
  Type     Reason                         Age                  From               Message
  ----     ------                         ----                 ----               -------
  Warning  FailedUpdateRegistrationToken  0s (x21 over 6m37s)  runner-controller  Updating registration token failed
```

I'll keep trying and will open a separate issue if I can't figure it out. Thanks for the fast reply!

**Comment by summerwind** [comment]
@acj Thank you for the contribution!

To issue a Registration Token, the user who issued the personal access token must have **admin** permission for the repository. I think that only *repo* scope is required for personal access token.

**Comment by acj** [comment]
Thanks, @summerwind. I updated the text to reflect that.

This can be done separately, but if the pods need to be privileged then we may want to note that in the readme as well:

>2020-03-25T12:04:14.250Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "runner", "request": "default/repo-runners-gdb69-6br77", "error": "Pod \"repo-runners-gdb69-6br77\" is invalid: spec.containers[1].securityContext.privileged: Forbidden: disallowed by cluster policy"}

**Comment by mumoshu** [comment]
@acj Thanks for the update 👍 

> the pods need to be privileged then we may want to note that in the readme as well:

Sounds good. Would providing readers an example PodSecurityPolicy to allow priv pods would also help?

**Comment by acj** [comment]
> Would providing readers an example PodSecurityPolicy to allow priv pods would also help?

@mumoshu Yes, I think that's a good idea.

Thanks, all, for the fast feedback and for building this controller :)

**Pull request merged**
