### PR TITLE
Update runner to 2.277.1

### PR DESCRIPTION
**Pull request by reiniertimmer**
Another day, another new runner release...

### CODE REVIEW

**Comment by reiniertimmer** [comment]
It seems integration tests are failing, but I've only updated the runner image. How come?

**Comment by callum-tait-pbx** [comment]
Line 18 in the `build-and-release-runners.yml` workflow needs updating too

**Comment by mumoshu** [comment]
@reiniertimmer Thanks for the PR!

> they are a bit unstable.

Yeah seems like so. I've seen the same failure several times. It seems like due to RunnerReplicaSetController sometimes take more than 5 seconds to create Runner resources. I'm still unsure if this is red herring or we really need to make the timeout longer yet.

**Comment by mumoshu** [comment]
> Line 18 in the build-and-release-runners.yml workflow needs updating too

Thanks. Addressed in b883bdf 👍

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks again for all your support!

**Comment by reiniertimmer** [comment]
@mumoshu what needs to be done to release the latest version of the docker image?

**Comment by mumoshu** [comment]
@reiniertimmer Thanks for the reminder! It turned out I have accidentally disabled the docker-push on the workflow. Once #347 is merged, a new docker image would be released shortly.

**Pull request merged**
